# --------------------------------------------------------------------------------------------
from FlagEmbedding import FlagReranker
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer

# --------------------------------------------------------------------------------------------

import uuid

# --------------------------------------------------------------------------------------------

from MetadataManager.MetadataStore.vdb.Chroma import ChromaVectorStore
from Utilities.base_utils import get_config_val

# --------------------------------------------------------------------------------------------


class FilterContext:
    """
    A class to provide filtering and scoring functionalities for retrieved information.

    Attr:
        - RerankerModel: Model for reranking retrieved information.
    """

    def __init__(self):
        """
        Initialize the FilterContext with pre-trained models.
        """
        models_repo = get_config_val("retrieval_config", ["models_repo"], True)
        scoring_configs = get_config_val("retrieval_config", ["scoring"], True)

        self.RerankerModel = FlagReranker(
            models_repo['path'] + "/" + scoring_configs["crossencoder"],
            use_fp16=True
        )

    def __ScoreResults_reranker__(self, base_query: str, retrieved_info: str):
        """
        Score the retrieved information using a reranker model.

        args:
            - base_query (str): The original query used for retrieval.
            - retrieved_info (str): Retrieved information to be scored.

        returns:
            - float: Score generated by the reranker model.
        """
        return self.RerankerModel.compute_score([base_query, retrieved_info])


    def __ScoreResults_keyword__(self, base_query: str, retrieved_info: str):
        """
        Score the retrieved information using a keyword-based model.

        args:
            - base_query (str): The original query used for retrieval.
            - retrieved_info (str): Retrieved information to be scored.

        returns:
            - float: Score generated by the BM25 algorithm.
        """
        tokenized_query = base_query.split(" ")
        tokenized_corpus = retrieved_info.split(" ")
        bm25 = BM25Okapi(tokenized_corpus)
        return max(bm25.get_scores(tokenized_query))


    def ScoreResults(self, base_query: str, retrieved_info: str) -> dict:
        """
        Score the retrieved information using available models.

        args:
            - base_query (str): The original query used for retrieval.
            - retrieved_info (str): Retrieved information to be scored.

        returns:
            - dict: Scores generated by different scoring models.
        """
        return {
            'reranker': self.__ScoreResults_reranker__(base_query, retrieved_info),
            'keyword':  self.__ScoreResults_keyword__(base_query, retrieved_info),
        }

# --------------------------------------------------------------------------------------------

class ManageInformation:
    """
    A class for managing information in a database.

    attr:
        - dbName (str): Name of the database being managed.
        - client: Client object for interacting with the database.
        - embedding_model: Sentence embedding model for generating embeddings.
    """

    def __init__(self):
        """
        Initialize the ManageInformation instance.
        """
        models_repo = get_config_val("retrieval_config", ["models_repo"], True)
        indexing_configs = get_config_val("retrieval_config", ["indexing"], True)
        self.vectordb_configs = get_config_val("retrieval_config", ["vectordb"], True)

        self.dbName = self.vectordb_configs["name"]
        self.vdb = None
        self.embedding_model = SentenceTransformer(
            models_repo['path'] + "/" + indexing_configs["model"]
        )
        self.FilterScoreObj = FilterContext()

    def initialize_client(self):
        """
        Initialize the vector store connection.

        Notes:
            - Currently supports 'chroma'. Swap ChromaVectorStore for any
              other BaseVectorStore implementation to change backends.
        """
        if self.dbName == 'chroma':
            self.vdb = ChromaVectorStore()
            self.vdb.connect(
                sessions_args={
                    'path': self.vectordb_configs["path"],
                    'host': "0.0.0.0",
                    'port': "5432"
                },
                session_type='local'
            )

    def add_new_data(self, data, data_metadata, vdb_metadata):
        """
        Add new data to the vector store.

        Args:
            data: Data to be added.
            data_metadata: Metadata for the data.
            vdb_metadata: Metadata specific to the virtual database (vdb).

        Returns:
            - str: Message indicating the success of the operation.
        """
        embedding_data = [
            {
                'documents': str(data),
                'embedding': self.embedding_model.encode(str(data)).tolist(),
                'metadata': data_metadata,
                'id': str(uuid.uuid3(uuid.NAMESPACE_DNS, str(data)))
            }
        ]

        self.vdb.add_data(embedding_data, vdb_metadata)

        return "Success"

    def get_data(self, query, vdb_metadata):
        """
        Retrieve data from the vector store and score each result.

        Args:
            query: Query to retrieve data.
            vdb_metadata: Metadata specific to the virtual database.

        Returns:
            dict: Scored results containing retrieved data, distance, and scores.
        """
        query_embed = self.embedding_model.encode(query).tolist()
        retrieved_info = self.vdb.get_data(query_embed, vdb_metadata)

        results_scored = {}
        for ind in range(len(retrieved_info['ids'][0])):
            results_scored[retrieved_info['ids'][0][ind]] = {
                'data':     retrieved_info['documents'][0][ind],
                'metadata': retrieved_info['metadatas'][0][ind],
                'distance': retrieved_info['distances'][0][ind],
                'scores':   self.FilterScoreObj.ScoreResults(
                                query, retrieved_info['documents'][0][ind]
                            )
            }

        return results_scored

# --------------------------------------------------------------------------------------------
