models_repo:
  path : 'C:/Users/mehul/Documents/Projects - GIT/Agents/Decompose KG from Code/pythonProject/Model'

# ---------------------------------------------------------


indexing:
  model: 'mixedbread-ai/mxbai-embed-large-v1'


# ---------------------------------------------------------


scoring:
  crossencoder: 'mixedbread-ai/mxbai-rerank-base-v1'
  bias_detection: "d4data/bias-detection-model"


# ---------------------------------------------------------


vectordb:
  name: 'chroma'
  path: 'C:\Users\mehul\Documents\Projects - GIT\Agents\SQLCoder\MetadataManager\MetadataStore\MetadataStorage\vdb'
  metadata:
    collection_name: 'tableScan'
    sim_metric: 'cosine'
    n_chunks: 5


# ---------------------------------------------------------


relationdb:
  name: 'networkx'
  path: 'C:\Users\mehul\Documents\Projects - GIT\Agents\SQLCoder\MetadataManager\MetadataStore\MetadataStorage\relationsdb\Relations.pickle'
  viz: 'C:\Users\mehul\Documents\Projects - GIT\Agents\SQLCoder\MetadataManager\MetadataStore\MetadataStorage\relationsdb\DataMap.html'


# ---------------------------------------------------------

tableMDdb:
  info_type : "table"
  dbName : "tableMetadata"
  tableDescName : "tableDesc"
  tableColName : "tableColMetadata"
